### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Umaroth** [abramhindle/ttwl-cli-saveedit#1]
I've used the editor several times before without issue but now it seems to be not working

No matter what button I select or which save file I try to edit, the program just stalls on whatever the first step is ("Randomizing GUID",  "Turning Weapons Primordial", etc) and never moves on.

Previously, it worked as expected, now it does not. Maybe a game update changed the save files?

**Comment by abramhindle** [comment]
The API changed and I have patched the problem. Please re-open this issue if you are still experiencing problems.

**Comment by Umaroth** [comment]
Thank you! It's resolved
