### ISSUE TITLE
Politely requesting Chaos 100 option in Wonderlands sav file editor

### ISSUE THREAD

**Issue by Dejakester** [abramhindle/ttwl-cli-saveedit#11]
Today gearbox changed chaos max to chaos 100... 
I do plan to run my mains up to 100 
but I have a ton of other toons
and I have found the previous level max thing very useful

**Comment by abramhindle** [comment]
Done.

**Comment by abramhindle** [comment]
Please check it out (hard refresh or use incognito mode). If it works then close the ticket, if it doesn't then try to tell me why.

**Comment by Dejakester** [comment]
It works
at least the bits I am using
I haven't been using all the features
Thank you for your very expeditious response
