### ISSUE TITLE
I can't get all the lucky dice taken

### ISSUE THREAD

**Issue by SkulletHell** [abramhindle/ttwl-cli-saveedit#12]
I check the option on the website and download the save and the data is still there, I have already deactivated the steam cloud and the 2k itself and deleted all the saves and the folder including but they are still in the save, I would be able to pass the save to you try to take?

**Comment by abramhindle** [comment]
The lucky dice are in the profile. They typically are not in the save files.
https://abramhindle.github.io/ttwl-cli-saveedit/profile.html
