### ISSUE TITLE
--backstory argument missing?

### ISSUE THREAD

**Issue by DQuinn97** [abramhindle/ttwl-cli-saveedit#2]
I might just be stupid and completely missed it, but on using: 
`ttwl-save-edit 2.sav 4.sav --backstory idiot` 
I get this error: 
`ttwl-save-edit: error: unrecognized arguments: --backstory idiot`

I am in the right directory, and the editor works other than that line, so is it something Im still doing wrong or is that argument not available? Because in the [README-saves.md#backstory](https://github.com/abramhindle/ttwl-cli-saveedit/blob/master/README-saves.md#backstory) it does exist?

**Comment by abramhindle** [comment]
You probably have an older version. I have updated the pypi version to v0.0.12 so it should be in there. Please update your install and see if this works.
