### ISSUE TITLE
[Feature Request] Web version of Profile Editor

### ISSUE THREAD

**Issue by bmfrosty** [abramhindle/ttwl-cli-saveedit#5]
Mostly thinking about the buttons for things that a player would use once.  I have a very established profile on xbox, but I've been spending a lot of time getting things established (like myth rank on my xbox profile is about 440) on my steam deck.  Some of these are reasonably navigable by characters from nexusmods (lucky dice, some customizations, money, xp boost items), but it would be nice to have it easy establishing a new profile.

**Comment by abramhindle** [comment]
That's a good point. I will consider making a UI for the `ttwl-profile-edit`.

**Comment by abramhindle** [comment]
https://abramhindle.github.io/ttwl-cli-saveedit/profile.html
There it is!
