### ISSUE TITLE
[Feature Request] Blank saves with all missions/story unlocked

### ISSUE THREAD

**Issue by Immusama** [abramhindle/ttwl-cli-saveedit#7]
Not sure if I missed it but a way to "simply" have the game finished on level 40.
So you can try new classes out easily without going through the main story again.

**Comment by abramhindle** [comment]
I think this is beyond the scope of the save editor. This is just useful debug save files.

**Comment by abramhindle** [comment]
https://apocalyptech.com/games/bl-saves/wl.php try these?
