### ISSUE TITLE
Trouble Understanding

### ISSUE THREAD

**Issue by cptnbananajam** [abramhindle/ttwl-cli-saveedit#9]
I am using the editor, but like the bl3 editor I am not sure what a lot of the parts mean. Some are self explanatory, like Parts_Sm_twister. Though I am sure that isn't the whole thing. Is there a library or a video, or something that explains what the parts are? Like Part_Spell_Buffmeister. I can tell it is a bonus of some kind to a spell, unless I'm wrong about that. But I'm not sure what it exactly does. I feel like I need to know something about how the game is written to understand how to mod things. Is there anything you can recommend to help me out?

**Comment by abramhindle** [comment]
Run this script with python3 -i and you can explore the parts of the items. There's no manual. 

```
from ttwlsave import datalib
from ttwlsave.datalib import DataWrapper
from ttwlsave.datalib import WLItem
import csv

BL3COL = 2
DW = DataWrapper()

def create_item(item_serial_b64):
    new_item = WLItem.create(DW, 
        serial_number=datalib.WLSerial.decode_serial_base64(item_serial_b64),
        pickup_order_idx=666,
        is_favorite=False,
    )
    return new_item

def parts(item):
    print(item.eng_name)
    print(sorted([x[0] for x in item._parts]))
```

**Comment by cptnbananajam** [comment]
Follow up question. I run a ps4 save file, the editor can recognize pc, ps4, and save wizard files.  Don't have a save wizard key. Is there a way to just load it as a ps4 file without using save wizard?

**Comment by abramhindle** [comment]
I don't know anything about PS4, I suggest you speak to people in that community.
